default_plugins = true
default_bindings = true

[[plugins]]
section = "Operations"
command =  "iplugin restic_restore"
help = "Restore from restic"

[[bindings]]
key = "B"
command = "iplugin restic_restore"

[[wd_replacements]]
real = "Library/CloudStorage/OneDrive-RedCedarConsultancy,LLC"
repl = "=OneDrive="

[[wd_replacements]]
real = "Library/CloudStorage/OneDrive-SharedLibraries-RedCedarConsultancy,LLC"
repl = "=OneDrive Sharad="
