promptToReturnFromSubprocess: false

os:
  # I usually use lazygit embedded in nvim. For this, I use
  # https://github.com/willothy/flatten.nvim to simplify the setup without the
  # need for external applications.
  #
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
  editAtLineAndWait: "nvim +{{line}} {{filename}}"

gui:
  mouseEvents: false

  # skipDiscardChangeWarning: true
  skipSwitchWorktreeOnCheckoutWarning: true

  theme:
    activeBorderColor:
      - '#f2cdcd'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#f2cdcd'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'

  authorColors:
    '*': '#b4befe'

customCommands:
  # LESS="RX" removes F from LESS defaults so that we don't return
  - key: "<C-a>"
    command: 'LESS="RX" git gla || true' # "|| true" prevents SIGPIPE (141) error and confirmation
    context: "global"
    loadingText: "Running git gla"
    description: "View git gla in a popup"
    output: terminal
  - key: "<C-k>"
    command: 'LESS="RX" git lsf || true' # "|| true" prevents SIGPIPE (141) error and confirmation
    context: "global"
    loadingText: "Running git gla"
    description: "View git lsf in a popup"
    output: terminal
  - key: "<C-f>"
    description: 'Show diff against first parent'
    context: "commits"
    command: 'LESS="RX" git show --first-parent {{.SelectedLocalCommit.Hash}} || true' # "|| true" prevents SIGPIPE (141) error and confirmation
    output: terminal
